<h4><b>MBlock - MForm - OwlCarousel2 (Slider)</b></h4>

<p>Diese Modul dient dazu Bilder mittels des <a href="https://github.com/OwlCarousel2/OwlCarousel2" target="_blank">Owl Carousel 2</a> auszugeben.</p>

<br/>
<b>Voraussetzungen</b>
<p>
<ul>
    <li>MBlock Addon</li>
    <li>MForm Addon</li>
    <li>Redactor 2</li>
    <li>jQuery im Frontend</li>
    <li>OWL Dateien (JS / CSS)</li>
</ul>
</p>
<br/>
<p><b>Bitte beachten</b></p>
<p>Es werden nicht automatisch die benötigeten JS und CSS Dateien eingebunden!</p>
<p>Es werden die Dateien des JavaScript Plugins OwlCarousel in den Ordner <strong><i>./assets/owlcarousel</i></strong> kopiert. Somit stehen dort die erforderlichen JS und CSS Dateien zur Verfügung.</p>

<p>Die benötigten Dateien müssen also von Hand in das/die Frontend-Template/s eingebunden werden.</p>

<p>Eine Anleitung gibt es <a href="https://owlcarousel2.github.io/OwlCarousel2/docs/started-welcome.html" target="_blank">hier</a>.</p>
<p>Demos gibt es <a href="https://owlcarousel2.github.io/OwlCarousel2/demos/demos.html" target="_blank">hier</a>.</p>
<hr/>
<p><b>Hinweis</b></p>
<p>Grundsätzlich basiert der Output auf dem Bootstrap Carousel. Das Element im Slider-Markup ist nur ein Beispiel, wei man weitere gestalterische Elemente individuell pro Slide einbinden kann.<br></p>
<p>Die Inhalte der Formular-Blöcke lassen sich, nach dem ersten Hinzufügen des Moduls, mit Klick auf die Head <strong>Sliderbild</strong> einklappen, damit die Blöcke sich leichter sortieren lassen.<br>Die <strong>Expertenoptionen</strong> für das Owl Carousel lassen sich auch so ausklappen.</p>

<hr/>
<p>Es ist natürlich möglich die Dateien "von Hand" an anderer Stelle zu kopieren und auch auf andere Weise einzubinden...</p>
