<h4><b>Parallax</b></h4>

<p>Diese Modul dient dazu ein ParallaxBild auszugeben</p>

<br/>
<b>Voraussetzungen</b>
<p>
<ul>
  <li>jQuery im Frontend</li>
  <li>Enllax JS</li>
</ul>

<br/>
<p><b>Bitte beachten</b></p>
<p>Es wird nicht automatisch die benötigete JS Dateien!</p>
<p>Es wird ddas JavaScript Plugins Enllax in den Ordner <i>./assets/enllax</i> kopiert. Somit stehen diese Datei dort zur Verfügung.</p>

<p>Die benötigte Datei muss also von Hand in das/die Frontend-Template/s eingebunden werden.</p>

<p>Eine Anleitung gibt es <a href="http://mmkjony.github.io/enllax.js/" target="_blank">hier</a>.</p>

<hr/>
<p>Es ist natürlich möglich die Dateien "von Hand" an anderer Stelle zu kopieren und auch auf andere Weise einzubinden...</p>
