<h4><b>Bootstrap Modal Window zeitgesteuert einfügen</b></h4>
<p>Das Modul kann ein Infofenster (pop-up) im Bootstrap Modal Window Stil zeitgesteuert anzeigen. Kann beliebig im Slice eingebunden oder in einem eigenen Bereich des Templates verwendet werden.</p>


<br/>
<b>Voraussetzungen</b>
<p>
<ul>
  <li>yForm</li>
  <li>yForm / Tools</li>
  <li>Bootstrap im Frontend (CSS/JS)</li>
</ul>

<hr/>
<p>Diese Modul wurde von <a target="_blank" href="https://github.com/darwin26">Christian</a> entwicklet.</p>
