

package: modulsammlung
version: '1.9-beta'
author: Oliver Kreischer
supportpage: www.redaxo.org/de/forum

page:
    title: 'translate:title'
    perm: modulsammlung[]
    icon: rex-icon fa-plus-square
    subpages:
        install: { title: 'translate:install' }
        info: { title: 'translate:info'}
