# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: modulsammlung
version: '4.6.5'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/REX5-Modulsammlung/issues
info: 'Idee und Realisierung der ersten Version: Oliver Kreicher / concedra.de'
compile: 0

page:
    title: 'translate:title'
    perm: modulsammlung[]
    icon: rex-icon fa-plus-square
    pjax: false
    subpages:
        module: {title: 'translate:module'}
        module_mform_mblock: {title: 'translate:module_mform_mblock'}
        templates: {title: 'translate:templates'}
        info:
            title: 'Info'
            itemclass: 'pull-right'
            subpages:
                info: { title: 'Info'}
                moduluebersicht: { title: 'translate:moduluebersicht'}
                changelog: { title: 'translate:changelog'}
                lizenz: { title: 'translate:lizenz'}
