package: modulsammlung
version: '4.21.0'
author: 'Friends Of REDAXO'
version: '4.20.0'
supportpage: 'https://github.com/FriendsOfREDAXO/REX5-Modulsammlung/issues'
info: 'Idee und Realisierung der ersten Version: Oliver Kreischer / concedra.de'
compile: 0

page:
    title: 'translate:title'
    perm: modulsammlung[]
    icon: rex-icon fa-plus-square
    pjax: false
    subpages:
        module: {title: 'translate:module'}
        more_examples: {title: 'translate:more_examples'}
        templates: {title: 'translate:templates'}
        info:
            title: 'Info'
            itemclass: 'pull-right'
            subpages:
                info: { title: 'Info'}
                moduluebersicht: { title: 'translate:moduluebersicht'}
                templateuebersicht: { title: 'translate:templateuebersicht'}
                changelog: { title: 'translate:changelog'}
                lizenz: { title: 'translate:lizenz'}
requires:
    php: '>7.4'
    redaxo: '^5.13.0'
