

package: grid_modul_builder
version: '1.0-dev'
author: Oliver Kreischer
supportpage: www.redaxo.org/de/forum

page:
    title: 'translate:title'
    perm: grid_modul_builder[]
    icon: rex-icon fa-hand-spock-o
    subpages:
        install: { title: 'translate:install' }
        anleitung: { title: 'translate:anleitung'}


 
