# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: modulsammlung
version: '4.6.0'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/REX5-Modulsammlung/issues
info: 'Idee und Realisierung der ersten Version: Oliver Kreicher / concedra.de'
compile: 0

page:
    title: 'translate:title'
    perm: modulsammlung[]
    icon: rex-icon fa-plus-square
    pjax: true
    subpages:
        main: { title: 'translate:main' }
        templates: { title: 'Templates'}
        info:
          title: 'Info'
          itemclass: 'pull-right'
          subpages:
            info: { title: 'Info'}
            moduluebersicht: { title: 'Modulübersicht'}
            changelog: { title: 'Changelog'}
            lizenz: { title: 'Lizenz'}
