

package: grid_modul_builder
version: '1.0-dev'
author: Oliver Kreischer
supportpage: www.redaxo.org/de/forum

page:
    title: 'translate:title'
    perm: grid_modul_builder[]
    icon: rex-icon rex-plus-square
    subpages:
        install: { title: 'translate:install' }
        anleitung: { title: 'translate:anleitung'}


 fa-plus-square [&#xf0fe;]
