# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: modulsammlung
version: '4.1.6'
author: Oliver Kreischer
supportpage: www.redaxo.org/de/forum
compile: 1

page:
    title: 'translate:title'
    perm: modulsammlung[]
    icon: rex-icon fa-plus-square
    pjax: true
    subpages:
        main: { title: 'translate:main' }
        info:
          title: 'Info'
          subpages:
            info: { title: 'Info'}
            moduluebersicht: { title: 'Modulübersicht'}
            changelog: { title: 'Changelog'}
            lizenz: { title: 'Lizenz'}
