<h4><b>Bilderslider mit/ohne Text</b></h4>

<p>Diese Modul dient dazu Bilder mittels <a href="http://owlcarousel2.github.io/OwlCarousel2/" target="_blank">Owl Carousel 2</a> auszugeben.</p>

<br/>
<b>Voraussetzungen</b>
<p>
<ul>
  <li>jQuery im Frontend</li>
  <li>OWL Dateien (JS / CSS)</li>
</ul>

<br/>
<p><b>Bitte beachten</b></p>
<p>Es werden nicht automatisch die benötigeten JS und CSS Dateien eingbunden!</p>
<p>Es werden die Dateien des JavaScript Plugins OwlCarousel in den Ordner <i>./assets/owl_carousel</i> kopiert. Somit stehen dort die erforderlichen JS und CSS Dateien zur Verfügung.</p>

<p>Die benötigten Dateien müssen also von Hand in das/die Frontend-Template/s eingebunden werden.</p>

<p>Eine Anleitung gibt es <a href="http://owlcarousel2.github.io/OwlCarousel2/docs/started-welcome.html" target="_blank">hier</a>.</p>

<hr/>
<p>Es ist natürlich möglich die Dateien "von Hand" an anderer Stelle zu kopieren und auch auf andere Weise einzubinden...</p>
