<h4><b>Alle Bilder mit aus dem Medienpool mit Copyright anzeigen</b></h4>

<p>Alle Bilddateien (jpg,png,gif) im Medienpool deren Copyrightinfo ausgefüllt ist werden im Frontend ausgegeben. Ausnahmen bilden die Bilder bei denen im Medienpool das Feld "Nicht in der Copyrightliste ausgeben" aktiviert ist.</p>

<br/>
<p>
    <ul>
        <li>Der Media Manager Typ <i>bildercopyright</i> wird angelegt und kann konfiguriert werden.</li>
        <li>Das Meta Info Feld (Medien) <i>med_no_copyright_out</i> wird angelegt.</li>
    </ul>
</p>
