<div id="copyright_modul_input" >
  <div id="bereich1" class="">
    <div class="form-horizontal">
      <h3>Alle Bilder mit aus dem Medienpool mit Copyright anzeigen</h3>
        <div class="form-group">
          <div class="col-xs-12">
           Alle Bilddateien (jpg,png,gif) im Medienpool deren Copyrightinfo ausgefüllt ist werden im Frontend ausgegeben. Ausnahmen bilden die Bilder bei denen im Medienpool das Feld "Nicht in der Copyrightliste ausgeben" aktiviert ist.
          </div>
        </div>
    </div>
  </div>
</div>

<style>
#copyright_modul_input {
  background: #f5f5f5;
  padding: 10px 30px 30px 15px;
  border: 1px solid #9da6b2;
}

#copyright_modul_input h3 {
  font-size: 14px !important;
  padding: 10px;
  background: #DFE3E9;
  width: 100%;
  margin-bottom: 20px;
}

#copyright_modul_input .control-label {
  font-weight: normal;
  font-size: 12px !important;
}
</style>
