<h3>Text / Bild / Video / Link | 1-4 Spalten</h3>

<p>Redaxo Modul für die Pflege von Inhalten die auf einer responsiven Webseite ausgegeben werden.</p>
<br/>
<ul>
  <li>Der Media Manager Typ <i>standard</i> wird angelegt und kann konfiguriert werden.</li>
  <li>Das Meta Info Feld (Medien) <i>med_no_copyright_out</i> wird angelegt.</li>
</ul>
<br/>
<b>Voraussetzungen</b>
<ul>
  <li>Redactor oder MarkItUp (+Textile) Addon</li>
</ul>
