#sitemap ul {
    margin: 0;
    padding: 0;
}

#sitemap ul li {
    margin: 0 0 30px 0;
    padding: 0;
    list-style: none;
}

#sitemap ul li ul li {
    margin: 0 0 10px 0;
}

#sitemap ul li a {
    font-size: 20px;
    color: #33549d;
}

#sitemap ul li ul li {
    padding-left: 20px;
}

#sitemap ul li:first-child {
    padding-top: 10px;
}

#sitemap ul li:last-child {
    margin-bottom: 10px;
}

#sitemap ul li ul li a {
    color: #33549d;
    font-size: 18px;
}

#sitemap ul .artikel li a{
    font-size: 16px;
    font-style: italic;
}

#sitemap span {
    font-size: 12px;
}

#sitemap .warning strong {
  color: #f00;
}
