<div id="artikelliste" >
  <div id="bereich1" class="">
    <div class="form-horizontal">
      <h3>Artikelliste</h3>
        <div class="form-group">
          <div class="col-sm-9 col-sm-push-3">
            Keine Eingabe notwendig
          </div>
        </div>
    </div>
  </div>
</div>

<style>
#artikelliste {
  background: #f5f5f5;
  padding: 10px 30px 30px 15px;
  border: 1px solid #9da6b2;
}

#artikelliste h3 {
  font-size: 14px !important;
  padding: 10px;
  background: #DFE3E9;
  width: 100%;
  margin-bottom: 20px;
}
</style>
