<h4><b>Text / Downloads</b></h4>

<p>Redaxo Modul für die Pflege von Inhalten die auf einer responsiven Webseite ausgegeben werden.</p>
<br/>
<ul>
  <li>Das Template <i>0500 - Download Hilfstemplat</i> wird angelegt und kann benutzt werden.</li>
</ul>
<br/>
<p><b>Voraussetzungen</b></p>
<ul>
  <li> MarkItUp (+Textile) Addon<br/>Beim ersten Aufruf des Moduls wird das jeweilige Profil angelegt. Danach sollte MarkItUp funktionieren.</li>
</ul>
<br/>
<p><b>Installation</b></p>
<ul>
  <li>Es muss ein Hilfsartikel mit dem Template <i>0500 - Download Hilfstemplat</i> angelegt werden auf dem nachher aus dem Downloadmodul verwiesen wird). Der Artikel muss online sein.
  </li>
</ul>
