<h4><b>Google Maps Modul / Routenplaner</b></h4>

<p>Redaxo Modul für die Ausgabe einer Google Map mit einigen Konfigurationsmöglichkeiten und Ausgabe eines Routenplaners.</p>
<p>Für die Nutzung ist ein <b>Google Maps API Key erforderlich</b>. <a target="_blank" href="https://developers.google.com/maps/documentation/javascript/get-api-key?hl=de">Der kann API KEY hier angefordert werden.</a></p>
<p>Der API Key muss im Modulinput und im Moduloutput eingetragen werden.</a></p>
<br/>
<b>Voraussetzungen</b>
<p>
<ul>
  <li>Google Maps API Key</li>
  <li>jQuery im Frontend</li>
  <li>MarkItUp Addon<br/>Beim ersten Aufruf des Moduls wird das jeweilige Profil angelegt. Danach sollte MarkItUp funktionieren.</li>
</ul>
