<h4><b>Google Maps Modul mit vielen Markern aus einer yform Tabelle</b></h4>

<p>Das Modul erzeugt aus einer beliebigen yform Tabelle mit geocodierten Feldern eine Google Karte.</p>
<p>In der Moduleingabe kann der HTML Code für die Infowindows mit beliebigen Platzhaltern aus der Datenbank eingegeben werden.</p>
<p>Für die Infofenster stehen zwei Darstellungsmöglichkeiten zur Verfügung: zum einen als Standard Infowindows der Google Maps api. Zum andern als Overlay Elemente der Karte.</p>
<p>Der api Key für Google Maps api wird aus der Felddefinition der yform Tabelle entnommen. Dort muss der key eingetragen sein.</p>
<p>Das Modul wurde mit REDAXO 5.4 und yform 2.3 getestet. Weitere Infos im Quelltext.</p>
<p>CSS und JS stehen in der Modulausgabe, was den sofortigen Test des Moduls vereinfachen soll. Bitte diesen Code in eigene Dateien auslagern und aus der Modulausgabe löschen.</p>
<br/>
<b>Voraussetzungen</b>
<ul>
  <li>Das geniale yform Addon</li>
  <li>Das geniale yform geo Plugin</li>
  <li>Eine yform Tabelle mit geocodierten Feldern.</li>
</ul>
<p>
Fragen?<br>
Wolfgang Bund<br>
post@agile-websites.de<br>
http://agile-websites.de<br> 
</p>
