<h4><b>Einfache Artikelliste mit Fragementen</b></h4>

<p>Dies ist ein einfaches Beispiel um die Nutzung von Fragementen zu demonstrieren.</p>
<p>
<b>Fragmente werden in REDAXO eingesetzt, um wiederkehrende Code-Schnipsel übersichtlich zu verwalten. Fragmente sind PHP-Dateien und werden bei der Ausgabe geparst, sodass Variablen ausgegeben und verarbeitet werden können. </b></p>

<p>In diesem Beispiel werden die benötigten Fragmente in dem Ordner <i>/redaxo/src/addons/modulsammlung/fragments/</i> gespeichert.</p>
<p>Wenn die - oder eigene - Fragemente dauerhaft genutzt werden sollen sollten diese in dem Fragments-Ordner des eigenen AddOns liegen. Alternativ bietet sich die Nutzung der AddOns "Project" oder "Theme" an. Dort können Fragemente updatesicher gespeichert werden. Sofern dort kein Ordner <i>fragments</i> existiert ist der einfach "von Hand" anzulegen.</p>

<p>Die Fragmente werden nur geladen sopfern die jeweiligen AddOns aktiviert sind.</p>

<p>Weitere Infos zu Fragmnenten finden sich hier: <a href="https://redaxo.org/doku/master/fragmente" target="_blank">https://redaxo.org/doku/master/fragmente</a></p>


<hr/>
<p><i>Vielen Dank an Thomas Blum für dieses Beispiel.</i></p>
