<h4><b>Parallax (Skrollr)</b></h4>

<p>Diese Modul dient dazu ein Parallax Effekt zu ermöglichen.</p>

<br/>
<b>Voraussetzungen</b>
<p>
<ul>
  <li>jQuery im Frontend</li>
  <li>Skrollr JS</li>
</ul>

<br/>
<p><b>Bitte beachten</b></p>
<p>Die benötigte JS Datei (skrollr.min.js) wird am Ende der Modulausgabe eingebunden. Da gehört die nicht wirklich hin :-))</p>
<p>Die Datei wird automatisch in den Ordner <i>./assets/skrollr</i> kopiert. Somit steht diese Datei dort zur Verfügung.</p>

<p>Die benötigte Datei muss also von Hand in das/die Frontend-Template/s eingebunden werden und die Modulausgabe angepasst werden.</p>

<p>Eine Anleitung zu skrollr gibt es <a href="https://github.com/Prinzhorn/skrollr" target="_blank">hier</a>.</p>

<hr/>
<p>Es ist natürlich möglich die Dateien "von Hand" an anderer Stelle zu kopieren und auch auf andere Weise einzubinden...</p>
