<h4><b>Formulargenerator-Modul</h4>
 <p><strong>Kompatibel mit UiKit</strong></p>  
<p>Dieser Generator ermöglicht das Erstellen und Versenden von E-Mail-Formularen. Etwas einfacher als mit yForm.</p>
<p>Ein Standardformular ist direkt beim ersten Aufruf vorkonfiguriert</p>
<p>Eine ausführliche Hilfe findet man in den <a target="_blank" href="https://friendsofredaxo.github.io/tricks/">REDAXO tricks</a>
<hr>
<p> Die beiliegenden CSS-Stile sind nur ein Beispiel und werden bei UiKit nicht vollständig benötigt.</p>
