<div id="link_linkliste" class="modul-content">
  <div class="form-horizontal">
    <h3>Link / Linkliste Beispiel</h3>
    <div class="form-group">
      <label class="col-sm-3 control-label" for="headline-level">Link</label>
      <div class="col-sm-9">
        <div class="btn-group btn-group-vertical" data-toggle="buttons">
          REX_LINK[id=1 widget=1]
          <?php /* mit Preview = REX_MEDIA[id=1 widget=1 preview=1] */?>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-3 control-label" for="headline-level">Linkliste</label>
      <div class="col-sm-9">
        <div class="btn-group btn-group-vertical" data-toggle="buttons">
          REX_LINKLIST[id=1 widget=1]
        </div>
      </div>
    </div>
  </div>
</div>


<style>
#link_linkliste.modul-content {
  background: #f5f5f5;
  padding: 10px 30px 30px 15px;
  border: 1px solid #9da6b2;
}

#link_linkliste.modul-content h3 {
  font-size: 14px !important;
  padding: 10px;
  background: #DFE3E9;
  width: 100%;
  margin-bottom: 20px;
}

#link_linkliste.modul-content .control-label {
  font-weight: normal;
  font-size: 12px !important;
}
</style>






