<h4><b>Text / Bild / Video / Link | 1-4 Spalten</b></h4>

<p>Redaxo Modul für die Pflege von Inhalten die auf einer responsiven Webseite ausgegeben werden.</p>
<br/>
<ul>
  <li>Der Media Manager Typ <i>standard</i> wird angelegt und kann konfiguriert werden.</li>
</ul>
<br/>
<b>Voraussetzungen</b>
<p>
<ul>
  <li> MarkItUp Addon<br/>Beim ersten Aufruf des Moduls wird das jeweilige Profil angelegt. Danach sollte MarkItUp funktionieren.</li>
</ul>
</p>
