<h4><b>Bildergalerie (lightGallery)</b></h4>

<p>Diese Modul dient dazu Bilder mittels der <a href="http://unitegallery.net" target="_blank">lightGallery</a> auszugeben.</p>

<br/>
<b>Voraussetzungen</b>
<p>
<ul>
  <li>jQuery im Frontend</li>
  <li>lightGallery (AddOn)</li>
  <li>lightGallery Dateien (CSS)</li>
</ul>

<br/>
<p><b>Bitte beachten:</b></p>
<p>Es werden nicht automatisch die benötigeten JS und CSS Dateien eingbunden!</p>
<p>Die benötigten Dateien müssen also von Hand in das/die Frontend-Template/s eingebunden werden.</p>
<p>Eine Anleitung gibt es lightGallery-Addon.</p>

<hr/>
