<h4><b>Bildergalerie (lightGallery)</b></h4>

<p>Diese Modul dient dazu Bilder mittels der <a href="https://github.com/sachinchoolur/lightGallery/tree/1.2.21" target="_blank">lightGallery</a> auszugeben.</p>

<br/>
<b>Voraussetzungen</b>
<p>
<ul>
  <li>jQuery im Frontend</li>
  <li>lightGallery (AddOn)</li>
  <li>lightGallery Dateien (CSS/JS)</li>
</ul>

<hr/><br/>

<p><b>Bitte beachten:</b></p>
<ul>
    <li>Es werden nicht automatisch die benötigeten JS und CSS Dateien eingbunden!</li>
    <li>Die benötigten Dateien müssen von Hand in das/die Frontend-Template/s eingebunden werden.</li>
    <li>Eine Anleitung gibt es lightGallery-Addon.</li>
</ul>


