<h4><b>Sitemap</b></h4>
<p>Diese Modul stellt die Sitemap einer Webseite da.<p>
<p>Artikel, Startartikel und SEO Infos können ein- / ausgeschaltet werden.</p>
<p>Im laufendem Betrieb einer Webseite ist es wohl sinnvoller die SEO Infos auszuschalten :-)</p>

<br/><br/>
<p><b>Voraussetzungen</b></p>
<ul>
  <li>MarkItUp Addon<br/>Beim ersten Aufruf des Moduls wird das jeweilige Profil angelegt. Danach sollte MarkItUp funktionieren.</li>
  <li>Font Awesome</li>
</ul>
