<div id="beispielinhalte" class="modul-content">
  <div class="form-horizontal">
  <h3>Beispielinhalte ausgeben</h3>
  <div class="form-group">
    <div class="col-sm-9 col-sm-push-3">
      <strong>Keine Eingabe erforderlich</strong>
        <p>Im Frontend werden Beidspielinhalte ausgegeben.</p>
      </div>
    </div>
  </div>
</div>

<style>
#beispielinhalte {
  background: #f5f5f5;
  padding: 10px 30px 30px 15px;
  border: 1px solid #9da6b2;
}

#beispielinhalte h3 {
  font-size: 14px !important;
  padding: 10px;
  background: #DFE3E9;
  width: 100%;
  margin-bottom: 20px;
}
</style>
