<?php if(!rex::isBackend()) { ?>

<div class="container">
  <h1>Überschrift H1: Donec ullamcorper nulla non metus auctor fringilla.</h1>
  <h2>Überschrift H2: Maecenas faucibus mollis interdum.</h2>
  <h3>Überschrift H3: Nullam quis risus eget urna mollis ornare vel eu leo.</h3>
  <h4>Überschrift H4: Cras justo odio, dapibus ac facilisis in, egestas eget quam.</h4>
  <h5>Überschrift H5: Duis mollis, est non commodo luctus, nisi sem nec elit.</h5>
  <h6>Überschrift H6: Donec ullamcorper nulla non metus auctor fringilla.</h6>
</div>

<hr/>

<div class="container">
  <h1>Überschrift H1: Donec ullamcorper nulla non metus auctor fringilla.</h1>
  <p>Nullam quis risus eget urna mollis ornare vel eu leo. Donec ullamcorper nulla non metus auctor fringilla. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Donec sed odio dui. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>

  <p>Maecenas faucibus mollis interdum. Curabitur blandit tempus porttitor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Etiam porta sem malesuada magna mollis euismod. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.</p>

  <h2>Überschrift H2: Maecenas faucibus mollis interdum.</h2>
  <p>Nullam quis risus eget urna mollis ornare vel eu leo. Donec ullamcorper nulla non metus auctor fringilla. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Donec sed odio dui. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>

  <h3>Überschrift H3: Nullam quis risus eget urna mollis ornare vel eu leo.</h3>
  <p>Nullam quis risus eget urna mollis ornare vel eu leo. Donec ullamcorper nulla non metus auctor fringilla. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Donec sed odio dui. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>

  <h4>Überschrift H4: Cras justo odio, dapibus ac facilisis in, egestas eget quam.</h4>
  <p>Nullam quis risus eget urna mollis ornare vel eu leo. Donec ullamcorper nulla non metus auctor fringilla. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Donec sed odio dui. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>

  <h5>Überschrift H5: Duis mollis, est non commodo luctus, nisi sem nec elit.</h5>
  <p>Nullam quis risus eget urna mollis ornare vel eu leo. Donec ullamcorper nulla non metus auctor fringilla. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Donec sed odio dui. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>

  <h6>Überschrift H6: Donec ullamcorper nulla non metus auctor fringilla.</h6>
  <p>Nullam quis risus eget urna mollis ornare vel eu leo. Donec ullamcorper nulla non metus auctor fringilla. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Donec sed odio dui. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
</div>

<hr/>

<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-push-6">
      <dl>
         <dt>Webkit</dt>
         <dd>Das Open Source-Projekt »Webkit« ist Grundlage für mehrere Browser
            <dl>
               <dt>Chrome</dt><dd>Browser von Google, …</dd>
               <dt>Safari</dt><dd>Browser von Apple, …</dd>
            </dl>
         </dd>
         <dt>Internet Explorer</dt>
         <dd>Browser von Microsoft</dd>
      <dl>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6">
    <ol>
       <li>HTML strukturiert die Inhalte einer Seite
          <ul>
             <li>durch einfache Elemente wie Überschriften und Textabsätze</li>
             <li>durch verschachtelte Elemente wie Aufzählungen,
             Definitionslisten und Tabellen</li>
          </ul>
       </li>
       <li>CSS formatiert die Inhalte einer Webseite
          <ul>
             <li>CSS ändert Schriften, Farben und Hintergrundfarben</li>
             <li>CSS ändert Größe und Lage der HTML-Blöcke</li>
          </ul>
       </li>
    </ol>
    </div>
    <div class="col-sm-6">
      <ul>
        <li>Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</li>
        <li>Condimentum Ridiculus Dolor</li>
        <li>Quam Ultricies
          <ul>
            <li>Ullamcorper Ultricies Venenatis Ligula</li>
            <li>Fusce Dolor Condimentum</li>
          </ul>
        </li>
        <li>Vulputate Fringilla Sem</li>
      </ul>
    </div>
  </div>
</div>

<hr/>

<div class="container">
  <div class="row">

<p>Lorem <sup>superscript</sup> dolor <sub>subscript</sub> amet, consectetuer adipiscing elit. Nullam <a class="email" href="#">E-Mail Link</a> dignissim convallis est. Quisque aliquam. <cite>cite</cite>. Nunc iaculis suscipit dui. Nam sit amet sem. Aliquam <abbr title=" HTML Abkürzungs-Element">abbr</abbr> libero nisi, imperdiet at, tincidunt nec, gravida vehicula, nisl. Praesent mattis, massa quis luctus fermentum, <a href="#">interner Link</a> turpis mi volutpat justo, eu volutpat enim diam eget metus. Maecenas <a href="#" class="extern">externer Link</a> ornare tortor. Donec <a class="phone" href="#">1234 / 5458</a> sed tellus eget sapien fringilla nonummy. <acronym title="Syntactically Awesome Stylesheets">SASS</acronym> Mauris a ante. Suspendisse quam sem, consequat at, commodo vitae, feugiat in, nunc. Morbi imperdiet augue quis tellus.</p>

<blockquote>
  <p>Vestibulum id ligula porta felis euismod semper. Donec ullamcorper nulla non metus auctor fringilla. Nullam id dolor id nibh ultricies vehicula ut id elit. Nullam quis risus eget urna mollis ornare vel eu leo.</p>
  <cite>Fritz Brause Oktober 1969</cite>
</blockquote>

<pre>pre Fusce dapibus, tellus ac cursus commodo,
      tortor mauris condimentum nibh, ut fermentum
massa justo sit amet risus. Praesent commodo cursus magna,
        vel scelerisque nisl consectetur et.
Sed posuere consectetur est at lobortis.</pre>


<p>Code can be presented inline, like <code>&lt;?php bloginfo('stylesheet_url'); ?&gt;</code>, or within a <code>&lt;pre&gt;</code> block. Because we have more specific typographic needs for code, we&#8217;ll specify Consolas and Monaco ahead of the browser-defined monospace font.</p>
<pre><code>#container {
  float: left;
  margin: 0 -240px 0 0;
  width: 100%;
}</code></pre>



<p>
  <em>This is italic text, made with em.</em> <i>This is italic text as well, made with i.</i>
</p>
<p>
  <strong>This is bold text, made with strong.</strong> <b>This is bold text as well, made with b.</b>
</p>
<p>
  <u>This is underlined text, made with u.</u> <ins>This is inserted text, made with ins.</ins>
</p>
<p>
  <strike>This is deleted (strikethrough) text, made with strike.</strike> <s>This is also strikethrough text, but made with s.</s> <del>This is deleted text, made with del.</del>
</p>
<p>
  <code>This is computer code, made with code.</code> <tt>This is teletype text, made with tt.</tt>
</p>
<p>
  <kbd>This is text the user is supposed to enter in, or keyboard, made with kbd.</kbd> <var>This is a variable, made with var.</var> <samp>This is sample program output, made with samp.</samp>
</p>
<p>
  <small>This is small text, made with small.</small> <big>This is big text, made with big.</big>
</p>
<p>
  <cite>This is a citation, made with cite.</cite> This is a <q>short quotation</q> in the middle of a sentence, made with q.
</p>
<p>
  This sentence ends with a <sup>superscript</sup>. This sentence ends with a <sub>subscript</sub>.
</p>
<p>
  This is an abbreviation, made with abbr: <abbr>WWW</abbr>. This is an acronym, made with acronym: <acronym>NATO</acronym>. This is a term that needs a definition, made with dfn: <dfn>Yog-Sothoth</dfn>.
</p>

<p>
  This is an address with breaks:
</p>
<address>
  John Q. Public
  <br>123 Main Street
  <br>Anywhere, ST 12345
</address>
<p>
  This is a long quotation inside a blockquote:
</p>

  </div>
</div>


<hr/>

<div class="container-fluid">
      <div class="row">
        <p>fluid container</p>
    </div>
</div>


<div class="container">

  <div class="row">
    <div class="col-xs-12"><p>xs 12</p></div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-6"><p>xs 12 / sm 6</p></div>
    <div class="col-xs-12 col-sm-6"><p>xs 12 / sm 6</p></div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-4"><p>xs 12 / sm 4</p></div>
    <div class="col-xs-12 col-sm-4"><p>xs 12 / sm 4</p></div>
    <div class="col-xs-12 col-sm-4"><p>xs 12 / sm 4</p></div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-3"><p>xs 12 / sm 6 / md 3</p></div>
    <div class="col-xs-12 col-sm-6 col-md-3"><p>xs 12 / sm 6 / md 3</p></div>
    <div class="col-xs-12 col-sm-6 col-md-3"><p>xs 12 / sm 6 / md 3</p></div>
    <div class="col-xs-12 col-sm-6 col-md-3"><p>xs 12 / sm 6 / md 3</p></div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-6"><p>xs 12 / sm 6</p></div>
    <div class="col-xs-12 col-sm-3"><p>xs 12 / sm 6</p></div>
    <div class="col-xs-12 col-sm-3"><p>xs 12 / sm 6</p></div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-3"><p>xs 12 / sm 3</p></div>
    <div class="col-xs-12 col-sm-6"><p>xs 12 / sm 6</p></div>
    <div class="col-xs-12 col-sm-3"><p>xs 12 / sm 3</p></div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-3"><p>xs 12 / sm 3</p></div>
    <div class="col-xs-12 col-sm-3"><p>xs 12 / sm 3</p></div>
    <div class="col-xs-12 col-sm-6"><p>xs 12 / sm 6</p></div>
  </div>
   <div class="row">
    <div class="col-xs-12 col-sm-8"><p>xs 12 / sm 8</p></div>
    <div class="col-xs-12 col-sm-4"><p>xs 12 / sm 4</p></div>
  </div>
   <div class="row">
    <div class="col-xs-12 col-sm-4"><p>xs 12 / sm 4</p></div>
    <div class="col-xs-12 col-sm-8"><p>xs 12 / sm 8</p></div>
  </div>
</div>

<hr/>

<?php
$emailabsender = 'sender@mail.de';
$email         = 'empfaenger@mail.de';
$textdanke     = 'Danke';


$formular = '';

$yform = new rex_yform();

$form_data = '

objparams|form_id|hierdieformid
objparams|form_showformafterupdate|0
objparams|real_field_names|true


html||<div class="radiocheckboxwrapper">
radio|anrede|Anrede|&nbsp;Herr=1,&nbsp;Frau=2|no_db|1
html||</div>


text|name|Name|#placeholder:Name
validate|empty|name|Bitte geben Sie Ihren Namen an.|
text|email|E-Mail|#placeholder:E-Mail
validate|empty|email|Bitte geben Sie Ihre E-Mail Adresse an. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.|
validate|email|email|Bitte geben Sie eine richtige E-Mail Adresse an. |
textarea|nachricht|Nachricht|#placeholder:Nachricht
validate|empty|name|Bitte geben Sie eine Nachricht ein.|

html||<div class="radiocheckboxwrapper">
checkbox|label|&nbsp;Dies ist eine Checkbox|nein,ja|1|
checkbox|label1|&nbsp;Dies ist noch eine Checkbox|nein,ja|1|
checkbox|label2|&nbsp;Dies ist die dritte Checkbox|nein,ja|1|
html||</div>

html|ueberschrift|<h4>Überschrift</h4>

html|trenner|<p class="kleinertext">Sed posuere consectetur est at lobortis. Nullam quis risus eget urna mollis ornare vel eu leo. Etiam porta sem malesuada magna mollis euismod. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</p>

html||<div class="select-style">
select|selectdingsi|Select|Bitte wählen,1. Dingsi,2. Dingsbums,3. Irgendetwas||||
html||</div>


 mediafile|name|Datei Upload|groesseinkb|endungenmitpunktmitkommasepariert|1|min_err,max_err,type_err,empty_err|[no_db]|mediacatid|user



html|required|<p class="form-required">* Pflichtfelder</p>


action|email|'.$emailabsender.'|'.$email.'|Nachricht von der Webseite (Kontaktformular)|<b>Name:</b> ###name###<br/><b>E-Mail:</b> ###email###<br/><br/><b>Nachricht:</b><br/>###nachricht###

submit|label|Senden|||
action|showtext|'.$textdanke.'|||1

';

$yform->setFormData($form_data);

$url = rex_getUrl($this->getArticleId());
$yform->setObjectparams("form_action", $url);

if(!rex::isBackend()) {

echo '
  <div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
        <p>Formular</p>
    </div>
    <div class="col-xs-12 col-sm-6">
        '.$yform->getForm().'
    </div>
  </div>
  </div>
';
}
?>


<?php } else { ?>

<div id="beispielinhalte" class="bereichswrapper">
  <div class="form-horizontal output">
    <h2 class="ueberschrift" >Beispielinhalte ausgeben</h2>
      <div class="form-group">
        <div class="col-sm-9 col-sm-push-3">
        <p>Die Beispielinhalte werden im Frontend ausgegeben.</p>
        </div>
      </div>
  </div>
</div>

<style>
#beispielinhalte .bereichswrapper {
  margin: 5px 0 5px 0;
  background: #f5f5f5;
  padding: 5px 15px 5px 15px;
  border: 1px solid #9da6b2;
}

#beispielinhalte  h2.ueberschrift {
  font-size: 12px !important;
  padding: 0 10px 10px 10px;
  margin-bottom: 15px;
  width: 100%;
  font-weight: bold;
  border-bottom: 1px solid #31404F;
}

</style>
<?php }; ?>
