<div id="gist" class="modul-content">
    <div class="form-horizontal">
        <h3>Gist URL</h3>
        <div class="form-group">
            <label class="col-sm-3 control-label" for="headline-level">Vollständige URL des Gits</label>
            <div class="col-sm-9">
                <input class="form-control" name="REX_INPUT_VALUE[1]" value="REX_VALUE[1]" type="text" />
                <p class="smalltext">Z.B.: https://gist.github.com/olien/edb7d249e20086da66cd5f95d1f34cfb</p>
            </div>
        </div>
    </div>
</div>

<style>
    #gist.modul-content {
        background: #f5f5f5;
        padding: 10px 30px 30px 15px;
        border: 1px solid #9da6b2;
    }

    #gist.modul-content h3 {
        font-size: 14px !important;
        padding: 10px;
        background: #DFE3E9;
        width: 100%;
        margin-bottom: 20px;
    }

    #gist.modul-content .control-label {
        font-weight: normal;
        font-size: 12px !important;
    }
    #gist p.smalltext {
        margin-top: 2px;
        font-size: 10px;
    }


</style>






