<div id="interne_weiterleitung" class="modul-content">
  <div>
    <div class="form-horizontal">
      <h3>Interne Weiterleitung</h3>
        <div class="form-group">
        <label class="col-sm-3 control-label">Seite:</label>
        <div class="col-sm-9">
          REX_LINK[id=1 widget=1]
        </div>
      </div>
  </div>
</div>


<style>
#interne_weiterleitung.modul-content {
  background: #f5f5f5;
  padding: 10px 30px 30px 15px;
  border: 1px solid #9da6b2;
}

#interne_weiterleitung.modul-content h3 {
  font-size: 14px !important;
  padding: 10px;
  background: #DFE3E9;
  width: 100%;
  margin-bottom: 20px;
}

#interne_weiterleitung.modul-content .control-label {
  font-weight: normal;
  font-size: 12px !important;
}

#interne_weiterleitung.modul-content input.form-control,
#interne_weiterleitung.modul-content select.form-control,
#interne_weiterleitung.modul-content textarea.form-control {
  background: #fff !important;
}

</style>
