<h4><b>Bildergalerie (Unite Gallery)</b></h4>

<p>Diese Modul dient dazu Bilder mittels der <a href="http://unitegallery.net" target="_blank">UNITE Gallery</a> auszugeben.</p>

<br/>
<b>Voraussetzungen</b>
<p>
<ul>
  <li>jQuery im Frontend</li>
  <li>UNITE Gallery Dateien (JS / CSS)</li>
</ul>

<br/>
<p><b>Bitte beachten</b></p>
<p>Es werden nicht automatisch die benötigeten JS und CSS Dateien eingbunden!</p>
<p>Es wird der komplette Inhalt des Ordners <i>dist</i> von <a href="https://github.com/vvvmax/unitegallery" target="_blank" >hier</a> in den Ordner <i>./assets/unitegallery</i> kopiert. Somit stehen dort die erforderlichen JS und CSS Dateien zur Verfügung.</p>

<p>Die benötigten Dateien müssen also von Hand in das/die Frontend-Template/s eingebunden werden.</p>

<p>Eine Anleitung gibt es <a href="http://unitegallery.net/index.php?page=documentation#installing_the_gallery" target="_blank">hier</a>.</p>

<hr/>
<p>Es ist natürlich möglich die Dateien "von Hand" an anderer Stelle zu kopieren und auch auf andere Weise einzubinden...</p>
